[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Using pre-built React assets from build/ directory'"]

[phases.start]
cmd = "gunicorn propply_app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"

[variables]
PYTHON_VERSION = "3.11.0"
FLASK_ENV = "production"
CI = "false"
