services:
  - type: web
    name: propply-ai-frontend
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18.20.5
      - key: CI
        value: true
      - key: NODE_ENV
        value: production
    # Add your Supabase environment variables in Render dashboard:
    # REACT_APP_SUPABASE_URL
    # REACT_APP_SUPABASE_ANON_KEY
    # REACT_APP_STRIPE_PUBLISHABLE_KEY
